include:
  - docker-compose.yml

services:
  test-runner:
    build: .
    command: npx jest -i -c jest.integration.config.js
    environment:
      - SECRET
      - POSTGRES_URL
      - API_KEY
      - TEST_BASE_URL=http://app:3000
    volumes:
      - ./src:/home/node/app/src
      - ./jest.integration.setup.js:/home/node/app/jest.integration.setup.js
      - ./jest.integration.config.js:/home/node/app/jest.integration.config.js
    depends_on:
      app:
        condition: service_healthy
