service: minibox-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
