service: minibox-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: ./tsconfig.build.json

functions:
  api:
    handler: src/main.handler
    events:
      - httpApi:
          path: /
          method: get
