service: minibox-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors:
      allowedOrigins: [ '*' ]
      allowedHeaders: [ '*' ]
      allowedMethods: [ '*' ]

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

package:
  patterns:
    - '!**/migrations/*'

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: ./tsconfig.build.json
  customDomain:
    domainName: api.minibox.inolopesm.com
    endpointType: regional
    apiType: http

functions:
  api:
    handler: src/main.handler
    events: [ httpApi: GET / ]
  createSession:
    handler: src/main.createSession
    events: [ httpApi: POST /sessions ]
  createUser:
    handler: src/main.createUser
    events: [ httpApi: POST /users ]
  findProducts:
    handler: src/main.findProducts
    events: [ httpApi: GET /products ]
  createProduct:
    handler: src/main.createProduct
    events: [ httpApi: POST /products ]
